// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "9412d6e5-700f-4fe5-9ac7-1520c97219a0";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onDistanceCmChange();
void onTemperatureChange();
void onAlarmCountChange();
void onStateChange();

float distanceCm;
CloudTemperatureSensor temperature;
int alarmCount;
int state;
bool systemOnline;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(distanceCm, READWRITE, ON_CHANGE, onDistanceCmChange);
  ArduinoCloud.addProperty(temperature, READWRITE, ON_CHANGE, onTemperatureChange);
  ArduinoCloud.addProperty(alarmCount, READWRITE, ON_CHANGE, onAlarmCountChange);
  ArduinoCloud.addProperty(state, READWRITE, ON_CHANGE, onStateChange);
  ArduinoCloud.addProperty(systemOnline, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
